### ISSUE TITLE
Exception thrown when delete a book.

### ISSUE THREAD

**Issue by sabrinasun** [sabrinasun/befree#51]
Reproduce steps:
1. click on add to bag button in home page. 
2. click on cart to check out
3. either register or login, to check out. 
4. click on the delete link in the checkout page. 

KeyError at /view_bag/delete/33/
33
Request Method:	GET
Request URL:	http://djangoupgrade.buddhistexchange.com/view_bag/delete/33/
Django Version:	1.10.5
Exception Type:	KeyError
Exception Value:	
33
Exception Location:	/home/befree/webapps/be_djangoupgrade/myproject/core/views.py in view_bag_delete, line 244
Python Executable:	/usr/local/bin/python3
Python Version:	3.5.2
Python Path:	
['/home/befree/webapps/be_djangoupgrade',
 '/home/befree/webapps/be_djangoupgrade/myproject',
 '/home/befree/.virtualenvs/be_upgrade/lib/python3.5/site-packages',
 '/usr/local/lib/python35.zip',
 '/usr/local/lib/python3.5',
 '/usr/local/lib/python3.5/plat-linux',
 '/usr/local/lib/python3.5/lib-dynload',
 '/usr/local/lib/python3.5/site-packages']
Server time:	Tue, 7 Feb 2017 21:52:21 -0600

**Comment by vaimdev** [comment]
Hi, I have investigated it was due to old implementation which keep the session key with integer value , which is not allowed in JSON format. 
http://stackoverflow.com/questions/24943240/weird-session-object-behavior-in-django

This required a thorough check of the code of request.session for cart, give me some time.

**Comment by vaimdev** [comment]
Issue fixed. session dict key is now all standarize to string instead of integer to comply to JSON format
