### ISSUE TITLE
Form - linked form - link field validation

### ISSUE THREAD

**Issue by sabrinasun** [sabrinasun/befree#57]
link fields shouldn't require http:// prefix. say www.yahoo.com should be allowed as a link. subdomains should also be allowed as a link, say djangoupgrade.buddhistexchange.com/book/1

**Comment by vaimdev** [comment]
Hi,
The field is implemented as URLField , therefore , the http:// is required , if we change to normal CharField , no validation of URL will be carried out. is it ok ?

**Comment by sabrinasun** [comment]
Quite a few existing forms have url, follow the same behavior is fine. login and click on Update Profile, follow the behavior of this url field. Replace below link [userid] with your id.
http://djangoupgrade.buddhistexchange.com/accounts/[userid]/edit/
![url](https://cloud.githubusercontent.com/assets/877632/24275341/1d8d71fe-1005-11e7-85ff-2c8b6521c47c.png)

**Comment by vaimdev** [comment]
Ok, will make this change

**Comment by vaimdev** [comment]
Hi , regarding this, if we don't check on the scheme/protocol (http:// or https:// etc), when display on post on page, it will show as relative path to current website , i.e : if I maintain as www.google.com , it will display as http://djangoupgrade.buddhistexchange.com/www.google.com .

Therefore, in order to display properly , we need to prepend either http:// or https:// to the url value that key in by user if we do not want to validate the protocol. In this case, should I assume all link need to display as http:// as prefix ?

**Comment by sabrinasun** [comment]
Yes, allow user to omit the http:// prefix. If prefix missing, assume http:// before insert to database.

**Comment by vaimdev** [comment]
Item fixed, and updated to test site.
